<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class SearchRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function all($keys =null)
    {
        $data = parent::all($keys);
        $data['token'] = $this->route('token');
        $data['search'] = $this->query('search');

        return $data;
    }
    public function rules()
    {
        return [
            'search'=>'required|string|max:50'
        ];
    }
    public function messages()
    {
        return [
//            'search'=>'You'
        ];

//        return parent::messages(); // TODO: Change the autogenerated stub
    }
}
